### ISSUE TITLE
Normal color codes dont work in scoreboard when using placeholders

### ISSUE THREAD

**Issue by RoboTitanII** [devblook/akropolis#7]
### Describe the bug

When using placeholder api to get a placeholder (for example your luck perms rank in the scoreboard), if there are color codes used in it (example &cOwner), the scoreboard will display "&cOwner" rather than "Owner" in red.

### Link to latest.log file

https://mclo.gs/clM7w8Y

### Steps to reproduce

1. Use a placeholder that uses the color format of "&"
2. Use this placeholder in something such as the scoreboard
3. reload the plugin or restart the server
4. Bug/issue should appear

### Expected behavior

Color code with format "&" in placeholders should still work when used in scoreboard

### Technical information

Paper
1.19.4
1.2.0

**Comment by zetastormy** [comment]
Hi, I just confirmed this issue. I will try to fix it as soon as I have some time, but in the mean time could you please try to use MiniMessage color codes? or does this break other plugins? Thank you.

**Comment by zetastormy** [comment]
Please, try version 1.2.1, as this seem to be fixed.

**Comment by zetastormy** [comment]
Please, make another bug report if you have an issue with the scoreboard. Thank you!
