### ISSUE TITLE
Add RGB color support for placeholders

### ISSUE THREAD

**Issue by DriftyDev** [devblook/akropolis#8]
### Is your feature request related to a problem?

Yes, when using a placeholder (Luckperms suffix) rgb chat formatting doesnt work.
![image](https://github.com/devblook/akropolis/assets/58635278/ecd8d687-2760-4e49-985a-e36414cd1181)
![image](https://github.com/devblook/akropolis/assets/58635278/48af1e4d-0345-477e-8906-b73ef838f76f)

### Describe the solution you'd like

Parse placeholders with miniMessages.

### Describe alternatives you've considered

When using normal hex (Prefix)
![image](https://github.com/devblook/akropolis/assets/58635278/f1b88e2d-e7dc-4fea-bbde-cadc7197927a)
![image](https://github.com/devblook/akropolis/assets/58635278/abe1bf6b-73ac-4c36-8edc-df5e7777e28b)

The scoreboard placeholders does turn bold but it doesnt color, btw same happens with chat.

**Comment by zetastormy** [comment]
I will try to fix this issue as soon as I can. Thank you for reporting!

**Comment by zetastormy** [comment]
Now that I think about it, a temporary solution might be using [MiniPlaceholders LuckPerms Expansion](https://github.com/MiniPlaceholders/MiniPlaceholders/wiki/Placeholders#luckperms), as Akropolis is compatible with it.

**Comment by zetastormy** [comment]
It seems to work fine now, sorry for the delay.
