### ISSUE TITLE
[Bug] Players can edit text on the sign without permission

### ISSUE THREAD

**Issue by Dreeam-qwq** [devblook/akropolis#9]
### Describe the bug

As the title said, player can edit text on the sign in the lobby

### Link to latest.log file

No error

### Steps to reproduce

1. Install akropolis with default config
2. Ensure options in world protection section are all enabled.
3. deop myself and rejoin server
4. Edit text on sigh

### Expected behavior

Players should not able to edit sign

### Technical information

Server version: 1.20.4

**Comment by zetastormy** [comment]
Sorry for the late response. I'm not able to reproduce this issue, at least with the latest version from the develop branch (5cb6adc) in Paper version 1.21-105-master@7e91a2c. Maybe it was another plugin causing this behavior?
